const { db, initSchema } = require('./database');

const SAMPLE_DEVICES = [
  {
    deviceId: 'dev_sam_s24u_01',
    deviceModel: 'Samsung Galaxy S24 Ultra',
    manufacturer: 'Samsung',
    brand: 'samsung',
    androidVersion: 'Android 15',
    apiLevel: 35,
    appVersion: '1.0.0',
    screenResolution: '1440x3120',
    screenDpi: 505,
    country: 'India',
    countryCode: 'IN',
    city: 'Mumbai',
    latitude: 19.0760,
    longitude: 72.8777,
    ipAddress: '103.21.124.55',
    batteryLevel: 92,
    minutesAgo: 2
  },
  {
    deviceId: 'dev_sam_s23p_02',
    deviceModel: 'Samsung Galaxy S23+',
    manufacturer: 'Samsung',
    brand: 'samsung',
    androidVersion: 'Android 14',
    apiLevel: 34,
    appVersion: '1.0.0',
    screenResolution: '1080x2340',
    screenDpi: 393,
    country: 'India',
    countryCode: 'IN',
    city: 'Ahmedabad',
    latitude: 23.0225,
    longitude: 72.5714,
    ipAddress: '115.240.180.12',
    batteryLevel: 78,
    minutesAgo: 5
  },
  {
    deviceId: 'dev_op_12_03',
    deviceModel: 'OnePlus 12 5G',
    manufacturer: 'OnePlus',
    brand: 'oneplus',
    androidVersion: 'Android 15',
    apiLevel: 35,
    appVersion: '1.0.0',
    screenResolution: '1440x3168',
    screenDpi: 510,
    country: 'India',
    countryCode: 'IN',
    city: 'Pune',
    latitude: 18.5204,
    longitude: 73.8567,
    ipAddress: '49.36.88.210',
    batteryLevel: 84,
    minutesAgo: 8
  },
  {
    deviceId: 'dev_pix_9p_04',
    deviceModel: 'Google Pixel 9 Pro XL',
    manufacturer: 'Google',
    brand: 'google',
    androidVersion: 'Android 15',
    apiLevel: 35,
    appVersion: '1.0.0',
    screenResolution: '1344x2992',
    screenDpi: 486,
    country: 'United States',
    countryCode: 'US',
    city: 'San Francisco',
    latitude: 37.7749,
    longitude: -122.4194,
    ipAddress: '64.233.160.1',
    batteryLevel: 95,
    minutesAgo: 1
  },
  {
    deviceId: 'dev_xia_14u_05',
    deviceModel: 'Xiaomi 14 Ultra',
    manufacturer: 'Xiaomi',
    brand: 'xiaomi',
    androidVersion: 'Android 14',
    apiLevel: 34,
    appVersion: '1.0.0',
    screenResolution: '1440x3200',
    screenDpi: 522,
    country: 'India',
    countryCode: 'IN',
    city: 'Bengaluru',
    latitude: 12.9716,
    longitude: 77.5946,
    ipAddress: '157.48.92.14',
    batteryLevel: 65,
    minutesAgo: 12
  },
  {
    deviceId: 'dev_sam_fold6_06',
    deviceModel: 'Samsung Galaxy Z Fold 6',
    manufacturer: 'Samsung',
    brand: 'samsung',
    androidVersion: 'Android 15',
    apiLevel: 35,
    appVersion: '1.0.0',
    screenResolution: '1856x2160',
    screenDpi: 374,
    country: 'United States',
    countryCode: 'US',
    city: 'New York',
    latitude: 40.7128,
    longitude: -74.0060,
    ipAddress: '172.56.21.90',
    batteryLevel: 70,
    minutesAgo: 14
  },
  {
    deviceId: 'dev_op_open_07',
    deviceModel: 'OnePlus Open',
    manufacturer: 'OnePlus',
    brand: 'oneplus',
    androidVersion: 'Android 14',
    apiLevel: 34,
    appVersion: '1.0.0',
    screenResolution: '2268x2440',
    screenDpi: 426,
    country: 'United Kingdom',
    countryCode: 'GB',
    city: 'London',
    latitude: 51.5074,
    longitude: -0.1278,
    ipAddress: '82.165.197.1',
    batteryLevel: 88,
    minutesAgo: 6
  },
  {
    deviceId: 'dev_pix_8p_08',
    deviceModel: 'Google Pixel 8 Pro',
    manufacturer: 'Google',
    brand: 'google',
    androidVersion: 'Android 15',
    apiLevel: 35,
    appVersion: '1.0.0',
    screenResolution: '1344x2992',
    screenDpi: 489,
    country: 'Germany',
    countryCode: 'DE',
    city: 'Berlin',
    latitude: 52.5200,
    longitude: 13.4050,
    ipAddress: '91.198.174.192',
    batteryLevel: 60,
    minutesAgo: 25
  },
  {
    deviceId: 'dev_vivo_x100_09',
    deviceModel: 'Vivo X100 Pro',
    manufacturer: 'Vivo',
    brand: 'vivo',
    androidVersion: 'Android 14',
    apiLevel: 34,
    appVersion: '1.0.0',
    screenResolution: '1260x2800',
    screenDpi: 453,
    country: 'United Arab Emirates',
    countryCode: 'AE',
    city: 'Dubai',
    latitude: 25.2048,
    longitude: 55.2708,
    ipAddress: '94.200.12.8',
    batteryLevel: 81,
    minutesAgo: 10
  },
  {
    deviceId: 'dev_op_11r_10',
    deviceModel: 'OnePlus 11R',
    manufacturer: 'OnePlus',
    brand: 'oneplus',
    androidVersion: 'Android 14',
    apiLevel: 34,
    appVersion: '1.0.0',
    screenResolution: '1240x2772',
    screenDpi: 450,
    country: 'India',
    countryCode: 'IN',
    city: 'New Delhi',
    latitude: 28.6139,
    longitude: 77.2090,
    ipAddress: '182.72.10.4',
    batteryLevel: 75,
    minutesAgo: 4
  },
  {
    deviceId: 'dev_sam_a55_11',
    deviceModel: 'Samsung Galaxy A55 5G',
    manufacturer: 'Samsung',
    brand: 'samsung',
    androidVersion: 'Android 14',
    apiLevel: 34,
    appVersion: '1.0.0',
    screenResolution: '1080x2340',
    screenDpi: 390,
    country: 'India',
    countryCode: 'IN',
    city: 'Surat',
    latitude: 21.1702,
    longitude: 72.8311,
    ipAddress: '117.200.45.19',
    batteryLevel: 94,
    minutesAgo: 3
  },
  {
    deviceId: 'dev_redmi_n13_12',
    deviceModel: 'Redmi Note 13 Pro+',
    manufacturer: 'Xiaomi',
    brand: 'xiaomi',
    androidVersion: 'Android 14',
    apiLevel: 34,
    appVersion: '1.0.0',
    screenResolution: '1220x2712',
    screenDpi: 446,
    country: 'India',
    countryCode: 'IN',
    city: 'Kolkata',
    latitude: 22.5726,
    longitude: 88.3639,
    ipAddress: '14.139.210.5',
    batteryLevel: 52,
    minutesAgo: 45
  },
  {
    deviceId: 'dev_pix_7a_13',
    deviceModel: 'Google Pixel 7a',
    manufacturer: 'Google',
    brand: 'google',
    androidVersion: 'Android 14',
    apiLevel: 34,
    appVersion: '1.0.0',
    screenResolution: '1080x2400',
    screenDpi: 429,
    country: 'Japan',
    countryCode: 'JP',
    city: 'Tokyo',
    latitude: 35.6762,
    longitude: 139.6503,
    ipAddress: '133.242.18.90',
    batteryLevel: 73,
    minutesAgo: 7
  },
  {
    deviceId: 'dev_nothing_2_14',
    deviceModel: 'Nothing Phone (2)',
    manufacturer: 'Nothing',
    brand: 'nothing',
    androidVersion: 'Android 14',
    apiLevel: 34,
    appVersion: '1.0.0',
    screenResolution: '1080x2412',
    screenDpi: 394,
    country: 'India',
    countryCode: 'IN',
    city: 'Jaipur',
    latitude: 26.9124,
    longitude: 75.7873,
    ipAddress: '122.176.45.10',
    batteryLevel: 89,
    minutesAgo: 11
  },
  {
    deviceId: 'dev_moto_e50_15',
    deviceModel: 'Motorola Edge 50 Ultra',
    manufacturer: 'Motorola',
    brand: 'motorola',
    androidVersion: 'Android 14',
    apiLevel: 34,
    appVersion: '1.0.0',
    screenResolution: '1220x2712',
    screenDpi: 446,
    country: 'France',
    countryCode: 'FR',
    city: 'Paris',
    latitude: 48.8566,
    longitude: 2.3522,
    ipAddress: '195.154.12.8',
    batteryLevel: 42,
    minutesAgo: 60
  },
  {
    deviceId: 'dev_realme_gt6_16',
    deviceModel: 'Realme GT 6',
    manufacturer: 'Realme',
    brand: 'realme',
    androidVersion: 'Android 14',
    apiLevel: 34,
    appVersion: '1.0.0',
    screenResolution: '1264x2780',
    screenDpi: 450,
    country: 'India',
    countryCode: 'IN',
    city: 'Ahmedabad',
    latitude: 23.0225,
    longitude: 72.5714,
    ipAddress: '103.240.35.78',
    batteryLevel: 86,
    minutesAgo: 2
  },
  {
    deviceId: 'dev_sam_s22u_17',
    deviceModel: 'Samsung Galaxy S22 Ultra',
    manufacturer: 'Samsung',
    brand: 'samsung',
    androidVersion: 'Android 14',
    apiLevel: 34,
    appVersion: '1.0.0',
    screenResolution: '1440x3088',
    screenDpi: 500,
    country: 'India',
    countryCode: 'IN',
    city: 'Hyderabad',
    latitude: 17.3850,
    longitude: 78.4867,
    ipAddress: '115.111.45.89',
    batteryLevel: 68,
    minutesAgo: 18
  },
  {
    deviceId: 'dev_iqoo_12_18',
    deviceModel: 'iQOO 12 5G',
    manufacturer: 'Vivo',
    brand: 'vivo',
    androidVersion: 'Android 15',
    apiLevel: 35,
    appVersion: '1.0.0',
    screenResolution: '1260x2800',
    screenDpi: 453,
    country: 'India',
    countryCode: 'IN',
    city: 'Chennai',
    latitude: 13.0827,
    longitude: 80.2707,
    ipAddress: '121.242.180.2',
    batteryLevel: 91,
    minutesAgo: 9
  },
  {
    deviceId: 'dev_xia_13t_19',
    deviceModel: 'Xiaomi 13T Pro',
    manufacturer: 'Xiaomi',
    brand: 'xiaomi',
    androidVersion: 'Android 14',
    apiLevel: 34,
    appVersion: '1.0.0',
    screenResolution: '1220x2712',
    screenDpi: 446,
    country: 'Singapore',
    countryCode: 'SG',
    city: 'Singapore',
    latitude: 1.3521,
    longitude: 103.8198,
    ipAddress: '118.189.24.1',
    batteryLevel: 79,
    minutesAgo: 13
  },
  {
    deviceId: 'dev_poco_f6_20',
    deviceModel: 'Poco F6 Pro',
    manufacturer: 'Xiaomi',
    brand: 'xiaomi',
    androidVersion: 'Android 14',
    apiLevel: 34,
    appVersion: '1.0.0',
    screenResolution: '1440x3200',
    screenDpi: 526,
    country: 'India',
    countryCode: 'IN',
    city: 'Rajkot',
    latitude: 22.3039,
    longitude: 70.8022,
    ipAddress: '103.250.80.12',
    batteryLevel: 83,
    minutesAgo: 4
  }
];

async function seedTelemetry() {
  await initSchema();
  console.log('📱 Seeding connected device telemetry...');

  const now = Date.now();
  for (const d of SAMPLE_DEVICES) {
    const lastPing = now - d.minutesAgo * 60 * 1000;
    const firstSeen = now - (d.minutesAgo + 2880) * 60 * 1000; // 2 days ago
    const fcmToken = `fcm_${d.deviceId}_${Math.round(Math.random() * 1e8)}`;

    await db.runAsync(
      `INSERT INTO device_telemetry (
         deviceId, deviceModel, manufacturer, brand, androidVersion, apiLevel,
         appVersion, screenResolution, screenDpi, country, countryCode, city,
         latitude, longitude, ipAddress, fcmToken, batteryLevel, firstSeenAt, lastPingAt
       ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
       ON CONFLICT(deviceId) DO UPDATE SET
         lastPingAt = excluded.lastPingAt,
         batteryLevel = excluded.batteryLevel`,
      [
        d.deviceId,
        d.deviceModel,
        d.manufacturer,
        d.brand,
        d.androidVersion,
        d.apiLevel,
        d.appVersion,
        d.screenResolution,
        d.screenDpi,
        d.country,
        d.countryCode,
        d.city,
        d.latitude,
        d.longitude,
        d.ipAddress,
        fcmToken,
        d.batteryLevel,
        firstSeen,
        lastPing
      ]
    );

    // Sync FCM tokens
    await db.runAsync(
      `INSERT INTO fcm_tokens (token, deviceModel, appVersion, updatedAt)
       VALUES (?, ?, ?, ?)
       ON CONFLICT(token) DO UPDATE SET
         deviceModel = excluded.deviceModel,
         updatedAt = excluded.updatedAt`,
      [fcmToken, d.deviceModel, d.appVersion, lastPing]
    );
  }

  console.log(`✅ Successfully seeded ${SAMPLE_DEVICES.length} connected devices!`);
  process.exit(0);
}

seedTelemetry().catch(err => {
  console.error('Seed telemetry error:', err);
  process.exit(1);
});
